box: ubuntu:disco

build:
  steps:
    - script:
        name: Set up
        code: ./setup.sh
    - script:
        name: Inspect
        code: ./inspect.sh
    - script:
        name: Benchmark
        code: ./bench.py
